"""add is_approved to assessment_questions

Revision ID: 5cc6620d7da9
Revises: 2f080a22d3f2
Create Date: 2026-06-09 23:55:21.294250
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa




# revision identifiers, used by Alembic.
revision = '5cc6620d7da9'
down_revision = '2f080a22d3f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_questions', sa.Column('is_approved', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment_questions', 'is_approved')
    # ### end Alembic commands ###

